name: indbytes_test
description: A Flutter machine test project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  file_picker: ^6.0.0
  equatable: ^2.0.5
  image_picker: ^1.0.4
  open_filex: ^4.3.4
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true